### ISSUE TITLE
Properly publish typings

### ISSUE THREAD

**Issue by DevVersion** [SimplrJS/scss-bundle#25]
Thanks for `scss-bundle`. I have a few things I noticed recently:
* `dist/` and `@types/` are published inside of GitHub.
* `@types` folder is not published within NPM

And also, normally packages should have their typing files next to the source files.

**Comment by DovydasNavickas** [comment]
`@types` are not published into npm, that's a good gotcha.

And for `living near the source`.. It's not necessary.
https://github.com/SimplrJS/scss-bundle/blob/master/package.json#L5
This line specifies where type definitions are, which makes it easy to consume and self-govern the location of `.d.ts` file. I will publish the typings into npm now 👏

**Comment by DevVersion** [comment]
@DovydasNavickas I know that they don't **have** to be next to the sources. But it's a recommendation and makes the `types` property inside of the `package.json` more optional.

A lot of editors and even custom TypeScript compiler hosts only looks for the typings next to the `.js` file.

**Comment by DovydasNavickas** [comment]
If anyone has problems with editors or custom TypeScript compiler hosts, I guess they will fill the issue.

Our team is used to publishing `.d.ts` files into `@types` and specifying `types` property in `package.json`, which is there for everyone to consume.

What I'm saying is that if there's a feature that custom compiler hosts or editors omit, it's not really a package's fault.

And what `recommendation` do you have in mind?

Because what I found here:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
>Also note that if your main declaration file is named `index.d.ts` and lives at the root of the package (next to `index.js`) you do not need to mark the `"types"` property, though it is advisable to do so.

Says:
>though it is advisable to do so
Which means, it is advisable to set `"types"` property.

**Comment by DovydasNavickas** [comment]
I've also published latest beta without `@beta` tag.. Which makes it a bit more urgent to release the `v2.0.1`. Whenever you start using the v2, if no further changes are needed, please ping me here 👍 
I will drop the `-beta` and release a proper version.
